version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
  - source: restart_apache.sh
    destination: /var/www/html

permissions:
  - object: /var/www/html
    owner: apache
    group: apache
    mode: 755
  - object: /var/www/html/restart_apache.sh
    owner: root
    group: root
    mode: 750

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: restart_apache.sh
      timeout: 30
      runas: root

